### ISSUE TITLE
browserify build not found

### ISSUE THREAD

**Issue by huynhnguyen** [gforge/pngjs3#35]
hi there,
I follow your instruction to use pngjs3 on browser, but it seems to me the library does not have any build for browser yet. Please correct me if I am wrong!

**Comment by huynhnguyen** [comment]
here is my wepack configure.common.bable.js
```
import { join, resolve } from 'path';
import Bundle from './bundle.json';
const include = join(__dirname, 'src');

export default {
  entry: {
    [Bundle.main]: ['@babel/polyfill', './src/index.js'],
    [Bundle.min]: ['@babel/polyfill', './src/index.js'],
  },
  mode: 'development',
  devtool: 'inline-source-map',
  module: {
    rules: [
      {
        enforce: 'pre',
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'eslint-loader',
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
      },
      {
        test: /\.js$/,
        enforce: 'post',
        loader: 'ify-loader',
      }
    ],
  }
};
```
on my code, I import in both ways:
```
import { PNG } from 'pngjs3';
```
or
```
import { PNG } from 'pngjs3/browser';
```

**Comment by huynhnguyen** [comment]
here is my browserify declaration inside the package.json
```
"browserify": {
    "transform": [
      "pngjs3"
    ]
  },
```

**Comment by huynhnguyen** [comment]
hi,
I finally get it works, thanks for your great package.

**Comment by gforge** [comment]
You're welcome. 

What was the problem? In case you've missed it :grin: : https://www.reddit.com/r/ProgrammerHumor/comments/9rqms9/what_should_happen/

Please take the time to write an answer or even a suggestion for how the package docs may be improved upon to help others.

**Comment by huynhnguyen** [comment]
ah, it just works without clear explanation, I think the document should be updated as:
 import { PNG } from 'pngjs3';
not this:
import { PNG } from 'pngjs3/browser';

**Comment by gforge** [comment]
I've added version 10 to Travis but everything works. Could you clone the package and then check with `npm run test` if everything works?

I'm currently changing the API to a more consistent form without the PNG-object-centered export. I've also updated the README. It will be released soon, it would be nice to include your issuel.
