### ISSUE TITLE
sync read didn't work

### ISSUE THREAD

**Issue by yllan** [gforge/pngjs3#62]
Node.js v12.7.0

```javascript
const fs = require('fs')
const PNG = require('pngjs3')
PNG.sync.read(fs.readFileSync('file.png'))
```

Got the result:

```
Thrown:
TypeError: "list" argument must be an Array of Buffers
    at Function.concat (/Users/yllan/Projects/test/node_modules/pngjs3/dist/pngjs3.js:817:13)
    at parse (/Users/yllan/Projects/test/node_modules/pngjs3/dist/pngjs3.js:7117:28)
    at Object.read (/Users/yllan/Projects/test/node_modules/pngjs3/dist/pngjs3.js:7511:10)
```

**Comment by gforge** [comment]
Weird, is it a sync issue, a v12, or a general issue?

**Comment by yllan** [comment]
I can use async to load image without problem.
It seems like the `dist` contains generated code for `Buffer.concat`,
which conflict with the Buffer comes with node.

<img width="813" alt="Screen Shot 2019-08-14 at 12 28 21 PM" src="https://user-images.githubusercontent.com/76055/62994546-139a7080-be8f-11e9-993f-a191231587b5.png">

```javascript
Buffer.isBuffer = isBuffer;
function internalIsBuffer (b) {
  return !!(b != null && b._isBuffer)
}
```

There is no `_isBuffer` in Buffer object.

**Comment by gforge** [comment]
I've tested with the v12 and the tests seem to pass fine. Have you tried `npm run test`?

The sync is tested here:
https://github.com/gforge/pngjs3/blob/master/test/same_img_different_format-spec.js#L34

**Comment by UlyssesZh** [comment]
I may confirm the bug is still present (6.1.1, node 18). However, `npm run test` does pass, and I do not know why.
@gforge Could you please create a new dir and run `npm i pngjs3` in it, and run OP's code in it?
