### ISSUE TITLE
Browser example of creating a png from user image data

### ISSUE THREAD

**Issue by backspaces** [gforge/pngjs3#93]
Could you make an example or two of use of pngjs3 in the browser? I didn't see any on the readme or examples/ dir.

My use-case is that I have all the byte data for an image, basically an imageData object with width, height, data of an existing png image.

I get the data using a webgl stunt to avoid canvas issues, mainly alpha-premultiply and color space conversions. OTOH if pngjs3 can grab the image data for me, that would be great!

I then modify the image bytes for steganography usage using the two least significant bits of all 4 RGBA pixel values.

Finally I want to update the png image (or create a new one) with the modified data, writing it to the users download directory using a dataUrl of the data .. again a canvas approach, sigh.

I'm hoping that I could use pngjs3 to do this, in the browser. The dataUrl is just a convenience so no worries.

Here's the download stunt:
```
// download canvas as png. canvas can be a dataURL.
export function downloadCanvas(can, name = 'canvas.png') {
    const url = typeof can === 'string' ? can : can.toDataURL()
    const link = document.createElement('a')
    link.download = name
    link.href = url
    link.click()
}
```

**Comment by backspaces** [comment]
That was a bit verbose, maybe this is clearer:

In the browser, I want to read in a png, modify its data, and write it back out!

**Comment by gforge** [comment]
Sorry, but I have never used it in that way
